FROM ubuntu:xenial-20160818

RUN apt-get update && \
  apt-get install -y \
  curl \
  xz-utils \
  build-essential \
  automake \
  autoconf \
  libtool \
  pkg-config \
  intltool \
  libcurl4-openssl-dev \
  libssl-dev \
  libglib2.0-dev \
  libevent-dev \
  libminiupnpc-dev \
  libminiupnpc10 \
  libappindicator-dev \
  perl \
  libjson-perl 
  && apt-get clean all

ADD version.h /tmp/version.h
