use JSON;
use strict;


my %cfg = (
  "alt-speed-down"                 => 50,
  "alt-speed-enabled"              => JSON::false,
  "alt-speed-time-begin"           => 540,
  "alt-speed-time-day"             => 127,
  "alt-speed-time-enabled"         => JSON::false,
  "alt-speed-time-end"             => 1020,
  "alt-speed-up"                   => 10,
  "bind-address-ipv4"              => "192.168.3.11",
  "bind-address-ipv6"              => "::",
  "blocklist-enabled"              => JSON::true,
  "blocklist-url"                  => "http://www.example.com/blocklist",
  "cache-size-mb"                  => 256,
  "dht-enabled"                    => JSON::true,
  "download-dir"                   => "/home/transmission/done",
  "download-queue-enabled"         => JSON::false,
  "download-queue-size"            => 5,
  "encryption"                     => 1,
  "idle-seeding-limit"             => 30,
  "idle-seeding-limit-enabled"     => JSON::false,
  "incomplete-dir"                 => "/home/transmission/incomplete",
  "incomplete-dir-enabled"         => JSON::true,
  "lpd-enabled"                    => JSON::false,
  "message-level"                  => 3,
  "peer-congestion-algorithm"      => "lp",
  "peer-id-ttl-hours"              => 3,
  "peer-limit-global"              => 350,
  "peer-limit-per-torrent"         => 50,
  "peer-port"                      => 46983,
  "peer-port-random-high"          => 65535,
  "peer-port-random-low"           => 49152,
  "peer-port-random-on-start"      => JSON::false,
  "peer-socket-tos"                => "default",
  "pex-enabled"                    => JSON::true,
  "port-forwarding-enabled"        => JSON::false,
  "preallocation"                  => 1,
  "prefetch-enabled"               => 1,
  "queue-stalled-enabled"          => JSON::true,
  "queue-stalled-minutes"          => 30,
  "ratio-limit"                    => 2,
  "ratio-limit-enabled"            => JSON::false,
  "rename-partial-files"           => JSON::true,
  "rpc-authentication-required"    => JSON::true,
  "rpc-bind-address"               => "0.0.0.0",
  "rpc-enabled"                    => JSON::true,
  "rpc-password"                   => "",
  "rpc-port"                       => 9092,
  "rpc-url"                        => "/transmission/",
  "rpc-username"                   => "",
  "rpc-whitelist"                  => "127.0.0.1,192.168.3.*",
  "rpc-whitelist-enabled"          => JSON::true,
  "scrape-paused-torrents-enabled" => JSON::true,
  "script-torrent-done-enabled"    => JSON::true,
  "script-torrent-done-filename"   => "/home/transmission/scripts/done-script.sh",
  "seed-queue-enabled"             => JSON::false,
  "seed-queue-size"                => 10,
  "speed-limit-down"               => 20,
  "speed-limit-down-enabled"       => JSON::false,
  "speed-limit-up"                 => 5,
  "speed-limit-up-enabled"         => JSON::true,
  "start-added-torrents"           => JSON::true,
  "trash-original-torrent-files"   => JSON::false,
  "umask"                          => 18,
  "upload-slots-per-torrent"       => 10,
  "utp-enabled"                    => JSON::true
);
#$cfg{'xyz'} = JSON::JSON::true;

my $json = JSON->new->allow_nonref;
print $json->utf8(1)->pretty(1)->encode(\%cfg);
print (keys %ENV);
